@startuml

title __EGOVPGR's Class Diagram__\n

  package agent {
    class AgentFactory {
    }
  }
  

  package agent {
    package agent.internal {
      abstract class AndroidAgent {
      }
    }
  }
  

  package agent {
    package agent.internal {
      class AndroidAppAgent {
      }
    }
  }
  

  package agent {
    package agent.internal {
      class AndroidWebAgent {
      }
    }
  }
  

  package central {
    enum AppachhiCentral {
    }
  }
  

  package enums {
    enum ConfigType {
    }
  }
  

  package central {
    class Configuration {
    }
  }
  

  package control {
    abstract class Control {
    }
  }
  

  package utils {
    class DateFormatFileAppender {
    }
  }
  

  package enums {
    enum DesktopBrowser {
    }
  }
  

  package agent {
    package agent.internal {
      class DesktopWebAgent {
      }
    }
  }
  

  package enums {
    enum Direction {
    }
  }
  

  package agent {
    interface IAgent {
    }
  }
  

  package control {
    interface IControl {
    }
  }
  

  package agent {
    package agent.internal {
      interface IDriverActions {
      }
    }
  }
  

  package agent {
    package agent.internal {
      abstract class IOSAgent {
      }
    }
  }
  

  package agent {
    package agent.internal {
      class IOSAppAgent {
      }
    }
  }
  

  package agent {
    package agent.internal {
      class IOSWebAgent {
      }
    }
  }
  

  package page {
    interface IPage {
    }
  }
  

  package agent {
    package agent.internal {
      interface IWindowActions {
      }
    }
  }
  

  package enums {
    enum IdentificationPlatform {
    }
  }
  

  package page {
    package pagedef {
      class Identifier {
      }
    }
  }
  

  package enums {
    enum IdentifyBy {
    }
  }
  

  package utils {
    class IniReader {
    }
  }
  

  package utils {
    class JavaUtils {
    }
  }
  

  package utils {
    class JsonReader {
    }
  }
  

  package agent {
    package agent.internal {
      abstract class MobileAgent {
      }
    }
  }
  

  package agent {
    package agent.internal {
      class MobileAgentFactory {
      }
    }
  }
  

  package control {
    class MobileControl {
    }
  }
  

  package enums {
    enum MobileView {
    }
  }
  

  package central {
    class ObjectRepository {
    }
  }
  

  package page {
    abstract class Page {
    }
  }
  

  package page {
    package pagedef {
      class PageDef {
      }
    }
  }
  

  package enums {
    enum Platform {
    }
  }
  

  package agent {
    package agent.internal {
      abstract class WebAgent {
      }
    }
  }
  

  package agent {
    package agent.internal {
      class WebAgentFactory {
      }
    }
  }
  

  package control {
    class WebControl {
    }
  }
  

  AndroidAgent -up-|> MobileAgent
  AndroidAppAgent -up-|> AndroidAgent
  AndroidWebAgent -up-|> AndroidAgent
  AppachhiCentral o-- Configuration : centralConf
  AppachhiCentral o-- ObjectRepository : pageDefs
  Control -up-|> IControl
  Control o-- IPage : page
  Control o-- IAgent : agent
  Control o-- Platform : platform
  DateFormatFileAppender -up-|> FileAppender
  DesktopWebAgent -up-|> WebAgent
  IOSAgent -up-|> MobileAgent
  IOSAppAgent -up-|> IOSAgent
  IOSWebAgent -up-|> IOSAgent
  Identifier o-- IdentifyBy : by
  MobileAgent -up-|> WebAgent
  MobileControl -up-|> WebControl
  Page -up-|> IPage
  Page o-- Configuration : config
  Page o-- IAgent : agent
  Page o-- PageDef : pageDef
  Page o-- Platform : platform
  PageDef o-- Identifier : identifier
  WebAgent -up-|> IAgent
  WebAgent o-- Configuration : config
  WebControl -up-|> Control


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
