@startuml

title __ENUMS's Class Diagram__\n

  package enums {
    enum ConfigType {
      DATA_DIR
      APPS_DIR
      DRIVERS_DIR
      PAGEDEF_DIR
      SUITE_DIR
      SCREENSHOTS_DIR
      PLATFORM
      PLATFORM_VER
      DEVICE_NAME
      BROWSER
      APP_URL
      APP_FILE_NAME
      APP_PACKAGE
      ACTIVITY_MAIN
      UDID
      APPIUM_URL
      XCODE_CONF
      IOS_AUTOMATION_NAME
      ANDROID_AUTOMATION_NAME
      ALERT_BEHAVIOR
      IMPLICIT_WAIT
      EXPLICIT_WAIT
      SWIPE_TOP_FRACTION
      SWIPE_DOWN_FRACTION
      SWIPE_WAIT
      SCROLL_PIXEL_COUNT
      SCRREENSHOT_TSTAMP
      SCREENSHOTS_ON
      SCREENSHOT_ONLY_ON_ERROR
      NO_RESET
    }
  }
  

  package enums {
    enum DesktopBrowser {
      IE
      EDGE
      CHROME
      SAFARI
      FIREFOX
    }
  }
  

  package enums {
    enum Direction {
      UP
      DOWN
      LEFT
      RIGHT
    }
  }
  

  package enums {
    enum IdentificationPlatform {
      IOS
      ANDROID
      MWEB
      DESKTOP_WEB
    }
  }
  

  package enums {
    enum IdentifyBy {
      ID
      NAME
      CLASSNAME
      LINKTEXT
      PARTIALLINKTEXT
      CSS
      TAGNAME
      XPATH
      ACCESSIBILITY
    }
  }
  

  package enums {
    enum MobileView {
      NATIVE_APP
      WEBVIEW
    }
  }
  

  package enums {
    enum Platform {
      IOS
      IOS_WEB
      ANDROID
      ANDROID_WEB
      DESKTOP_WEB
      desktopWebPlatforms
      mobileNativePlatforms
      mobileWebPlatforms
      iosPlatforms
      platformIdMap
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
